<?php

namespace App\Filament\Resources\MessageTemplateResource\Pages;

use App\Filament\Resources\MessageTemplateResource;
use Filament\Actions\EditAction;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewMessageTemplate extends ViewRecord
{
    protected static string $resource = MessageTemplateResource::class;

    protected function getHeaderActions(): array
    {
        return [
            EditAction::make()
                ->color('warning'),
        ];
    }

    public function infolist(Infolist $infolist): Infolist
    {
        parent::infolist($infolist); // TODO: Change the autogenerated stub

        return $infolist
            ->schema([
                TextEntry::make('messageTemplateCategory.name')
                    ->label('Kategori'),

                TextEntry::make('title')
                    ->label('Judul'),

                Section::make('Isi Pesan')
                    ->schema([
                        TextEntry::make('message')
                            ->label('')
                            ->formatStateUsing(fn($state) => nl2br(e($state)))
                            ->html(),
                    ]),

                TextEntry::make('is_active')
                    ->label('Status')
                    ->formatStateUsing(fn($state) => $state ? 'Aktif' : 'Tidak Aktif')
                    ->badge()
                    ->color(fn($state) => $state ? 'success' : 'danger')
                    ->inlineLabel(),
            ]);
    }
}
