<?php

namespace App\Filament\Resources\RecurringInvoiceResource\Pages;

use App\Enums\RecurrenceFrequency;
use App\Enums\RecurringInvoiceStatus;
use App\Filament\Resources\RecurringInvoiceResource;
use App\Filament\Resources\UserResource;
use App\Models\RecurringInvoice;
use Filament\Infolists\Components\Group;
use Filament\Infolists\Components\RepeatableEntry;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;
use Filament\Support\Enums\FontWeight;

class ViewRecurringInvoice extends ViewRecord
{
    protected static string $resource = RecurringInvoiceResource::class;
    protected static ?string $title = 'Detail';

    public function infolist(Infolist $infolist): Infolist
    {
        parent::infolist($infolist); // TODO: Change the autogenerated stub

        return $infolist
            ->columns(3)
            ->schema([
            Group::make()
                ->schema([
                    // TODO Invoice To
                    Section::make('Invoice To')
                        ->icon('heroicon-o-user-circle')
                        ->iconColor('primary')
                        ->columns()
                        ->schema([
                            TextEntry::make('code')
                                ->inlineLabel()
                                ->prefix('#')
                                ->weight(FontWeight::Bold),
                            TextEntry::make('user.name')
                                ->label('Customer Name')
                                ->inlineLabel()
                                ->url(fn(RecurringInvoice $record): string => UserResource::getUrl('edit', ['record' => $record->user?->username]))
                                ->color('primary')
                                ->weight(FontWeight::Bold),

                            TextEntry::make('user.userProfile.phone')
                                ->label('Phone')
                                ->inlineLabel()
                                ->weight(FontWeight::Bold),

                            TextEntry::make('user.userProfile.company_name')
                                ->label('Company')
                                ->inlineLabel()
                                ->weight(FontWeight::Bold),
                        ]),

                    // TODO Bill To
                    Section::make('Bill To')
                        ->icon('heroicon-o-wallet')
                        ->iconColor('primary')
                        ->description(fn($state, RecurringInvoice $record) => $record->title ?? 'N/A')
                        ->columns()
                        ->schema([
                            TextEntry::make('date')
                                ->label('Date')
                                ->icon('heroicon-o-calendar')
                                ->date('d M Y H:i')
                                ->inlineLabel(),

                            TextEntry::make('due_date')
                                ->label('Due Date')
                                ->icon('heroicon-o-calendar')
                                ->date('d M Y H:i')
                                ->inlineLabel()
                                ->color('danger'),

                            TextEntry::make('recurrence_frequency')
                                ->label('Rpt. Frequency')
                                ->icon('heroicon-o-clock')
                                ->formatStateUsing(fn($state, RecurringInvoice $record) => $record->repeat_every . ' ' . RecurrenceFrequency::tryFrom($state)?->getLabel() ?? 'N/A')
                                ->inlineLabel(),

                            TextEntry::make('next_invoice_date')
                                ->label('Next Inv. Date')
                                ->icon('heroicon-o-calendar')
                                ->date('d M Y H:i')
                                ->inlineLabel(),
                        ]),

                    // TODO Line Items
                    Section::make('Line Items')
                        ->icon('heroicon-o-bookmark-square')
                        ->iconColor('primary')
                        ->schema([
                            RepeatableEntry::make('lineItems')
                                ->hiddenLabel()
                                ->columns(3)
                                ->schema([
                                    TextEntry::make('item.name'),
                                    TextEntry::make('qty'),
                                    TextEntry::make('rate')
                                        ->money('idr')
                                        ->weight(FontWeight::Bold)
                                ])
                        ]),
                ])
                ->columnSpan(['lg' => 2]),

            Group::make()
                ->schema([
                    Section::make('Status')
                        ->schema([
                            TextEntry::make('status')
                                ->hiddenLabel()
                                ->formatStateUsing(fn($state) => RecurringInvoiceStatus::tryFrom($state)?->getLabel() ?? 'N/A')
                                ->color(fn($state) => RecurringInvoiceStatus::tryFrom($state)?->getColor() ?? 'gray')
                                ->size(TextEntry\TextEntrySize::Large)
                                ->weight(FontWeight::Bold)
                                ->icon(fn($state) => RecurringInvoiceStatus::tryFrom($state)?->getIcon() ?? 'heroicon-o-question-mark-circle')
                        ]),

                    Section::make('Total')
                        ->schema([
                            TextEntry::make('total_price_before_discount')
                                ->label('Total Price (Before Discount)')
                                ->money('idr')
                                ->size(TextEntry\TextEntrySize::Large)
                                ->weight(FontWeight::Bold)
                                ->visible(fn(RecurringInvoice $record): bool => $record->discount > 0),

                            TextEntry::make('total_price')
                                ->label(fn($state, RecurringInvoice $record) => $record->discount > 0 ? 'Total Price (After Discount)' : 'Total')
                                ->hiddenLabel(fn($state, RecurringInvoice $record) => $record->discount <= 0)
                                ->money('idr')
                                ->size(TextEntry\TextEntrySize::Large)
                                ->weight(FontWeight::Bold)
                                ->color('primary'),
                        ]),
                ])
                ->columnSpan(['lg' => 1]),
        ]);
    }
}
