<?php

namespace App\Filament\Resources\ItemResource\Pages;

use App\Enums\ProductType;
use App\Filament\Resources\ItemResource;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewItem extends ViewRecord
{
    protected static string $resource = ItemResource::class;

    public function infolist(Infolist $infolist): Infolist
    {
        parent::infolist($infolist); // TODO: Change the autogenerated stub

        return $infolist
            ->schema([
                Section::make()
                    ->inlineLabel()
                    ->schema([
                        TextEntry::make('product_type')
                            ->badge()
                            ->color(fn($state): string => ProductType::tryFrom($state)?->getColor() ?? 'gray')
                            ->formatStateUsing(fn($state): string => ProductType::tryFrom($state)->getLabel())
                    ])
            ]);
    }
}
