<?php

namespace App\Filament\Resources;

use App\Filament\Resources\InvoiceResource\Pages;
use App\Filament\Resources\InvoiceResource\Schemas\InvoiceForm;
use App\Filament\Resources\InvoiceResource\Schemas\InvoiceTable;
use App\Filament\Resources\InvoiceResource\Widgets\InvoiceStatsOverview;
use App\Models\Invoice;
use BezhanSalleh\FilamentShield\Contracts\HasShieldPermissions;
use Exception;
use Filament\Forms\Form;
use Filament\Pages\SubNavigationPosition;
use Filament\Resources\Pages\Page;
use Filament\Resources\Resource;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class InvoiceResource extends Resource implements HasShieldPermissions
{
    protected static ?string $model = Invoice::class;
    protected static ?string $slug = 'invoices';
    protected static ?string $navigationGroup = 'Finance';
    protected static ?int $navigationSort = 1;
    protected static ?string $navigationIcon = 'heroicon-o-receipt-percent';

    public static function getNavigationBadge(): ?string
    {
        return self::getModel()::where('status', '!=', 'paid')
            ->whereBetween('due_date', [now(), now()->addDays(7)])
            ->count();
    }

    public static function getNavigationBadgeColor(): string|array|null
    {
        return 'warning';
    }

    /**
     * @return string|null
     */
    public static function getNavigationBadgeTooltip(): ?string
    {
        return 'Total invoices due within the next 7 days';
    }

    protected static SubNavigationPosition $subNavigationPosition = SubNavigationPosition::Top;

    public static function getPermissionPrefixes(): array
    {
        // TODO: Implement getPermissionPrefixes() method.
        return [
            'view_any',
            'view',
            'create',
            'update',
            'delete',
        ];
    }

    public static function form(Form $form): Form
    {
        return InvoiceForm::form($form);
    }

    /**
     * @throws Exception
     */
    public static function table(Table $table): Table
    {
        return InvoiceTable::table($table);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListInvoices::route('/'),
            'create' => Pages\CreateInvoice::route('/create'),
            'view' => Pages\ViewInvoice::route('/{record}'),
            'edit' => Pages\EditInvoice::route('/{record}/edit'),
        ];
    }

    public static function getEloquentQuery(): Builder
    {
        // TODO: Change the autogenerated stub
        $userRole = auth()->user()?->roles?->first()?->name ?? null;

        return parent::getEloquentQuery()
            ->with(['user', 'invoiceItems.item', 'invoicePayments.payment'])
            ->when($userRole === 'user', function (Builder $query) {
                $query->where('user_id', auth()->id())
                    ->where('status', '!=', 'draft');
            });
    }

    public static function getRecordSubNavigation(Page $page): array
    {
        return $page->generateNavigationItems([
            Pages\EditInvoice::class,
            Pages\ViewInvoice::class,
        ]);
    }

    public static function getGloballySearchableAttributes(): array
    {
        return ['code'];
    }

    public static function getWidgets(): array
    {
        return [
            InvoiceStatsOverview::class
        ];
    }
}
