<?php

namespace App\Models;

use App\Observers\InvoiceObserver;
use Illuminate\Database\Eloquent\Attributes\ObservedBy;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\HasOne;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

#[ObservedBy([InvoiceObserver::class])]
class Invoice extends Model implements HasMedia
{
    use InteractsWithMedia;

    protected $fillable = [
        'slug',
        'invoice_number',
        'serial_number',
        'code',
        'user_id',
        'recurring_invoice_id',
        'title',
        'date',
        'due_date',
        'discount',
        'note',
        'status',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'date' => 'date',
            'due_date' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Invoice $invoice) {
            $invoice->slug = Str::uuid()->toString();
            $invoice->serial_number = self::max('serial_number') + 1;
            $invoice->code = 'INV' . Str::padLeft($invoice->serial_number, 6, '0');
            $invoice->invoice_number = $invoice->code . '-' . now()->timestamp;
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function invoiceItems(): HasMany
    {
        return $this->hasMany(InvoiceItem::class, 'invoice_id');
    }

    public function invoicePayments(): HasMany
    {
        return $this->hasMany(InvoicePayment::class, 'invoice_id');
    }

    public function invoicePaymentPending(): HasOne
    {
        return $this->hasOne(InvoicePayment::class, 'invoice_id')
            ->whereHas('invoice', function ($query) {
                $query->where('status', 'pending');
            });
    }

    public function recurringInvoice(): BelongsTo
    {
        return $this->belongsTo(RecurringInvoice::class);
    }

    // More
    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    // TODO Attribute Accessors
    protected function totalPrice(): Attribute
    {
        $discount = $this->discount ?? 0;
        $total = $this->invoiceItems->sum(function ($item) {
            return $item->rate;
        });

        $totalAfterDiscount = $total - ($total * ($discount / 100));

        return Attribute::make(fn() => $totalAfterDiscount);
    }

    protected function totalPriceBeforeDiscount(): Attribute
    {
        return Attribute::make(
            get: fn() => $this->invoiceItems->sum('rate')
        );
    }

    protected function totalPaid(): Attribute
    {
        return Attribute::make(fn() => $this->invoicePayments->sum('amount_applied'));
    }

    protected function totalDue(): Attribute
    {
        return Attribute::make(fn() => $this->total_price - $this->total_paid);
    }
}
