<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia;
use Spatie\MediaLibrary\InteractsWithMedia;

class Item extends Model implements HasMedia
{
    use SoftDeletes, InteractsWithMedia;

    protected $fillable = [
        'slug',
        'serial_number',
        'code',
        'product_type',
        'name',
        'item_name',
        'unit',
        'rate',
        'description',
        'is_active'
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean'
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Item $item) {
            $item->slug = Str::uuid()->toString();
            $item->serial_number = self::max('serial_number') + 1;
            $item->code = 'I' . Str::padLeft($item->serial_number, 6, '0');
        });
    }

    // more
    public function getRouteKeyName(): string
    {
        return 'slug';
    }
}
