<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MessageTemplate extends Model
{
    protected $fillable = [
        'slug',
        'category',
        'title',
        'message',
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'is_active' => 'boolean',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MessageTemplate $messageTemplate) {
            $messageTemplate->slug = Str::uuid()->toString();
        });

        static::created(function (MessageTemplate $messageTemplate) {
            if ($messageTemplate->is_active) {
                self::where('category', $messageTemplate->category)
                    ->where('id', '!=', $messageTemplate->id)
                    ->update(['is_active' => false]);
            }
        });

        static::updated(function (MessageTemplate $messageTemplate) {
            if ($messageTemplate->is_active) {
                self::where('category', $messageTemplate->category)
                    ->where('id', '!=', $messageTemplate->id)
                    ->update(['is_active' => false]);
            }
        });
    }

    // TODO Scope
    #[Scope]
    protected function active(Builder $query): Builder
    {
        return $query->where('is_active', true);
    }
}
