<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class MessageTemplateCategory extends Model
{
    protected $fillable = [
        'slug',
        'code',
        'name',
        'placeholder',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (MessageTemplateCategory $messageTemplateCategory) {
            $messageTemplateCategory->slug = Str::uuid()->toString();
            $messageTemplateCategory->code = strtoupper(str_replace(' ', '-', $messageTemplateCategory->name));
        });
    }
}
