<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Str;

class Payment extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'slug',
        'user_id',
        'serial_number',
        'reference_number',
        'date',
        'amount',
        'payment_method',
        'bank_account_id',
        'note',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'date' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Payment $payment) {
            $payment->slug = Str::uuid()->toString();
            $payment->serial_number = self::max('serial_number') + 1;
            $payment->reference_number = 'REF' . Str::padLeft($payment->serial_number, 6, '0');
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function bankAccount(): BelongsTo
    {
        return $this->belongsTo(BankAccount::class);
    }

    public function invoicePayments(): HasMany
    {
        return $this->hasMany(InvoicePayment::class, 'payment_id');
    }
}
