<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class RecurringInvoice extends Model
{
    protected $fillable = [
        'slug',
        'invoice_number',
        'serial_number',
        'code',
        'user_id',
        'title',
        'date',
        'due_date',
        'recurrence_frequency',
        'repeat_every',
        'discount',
        'note',
        'status',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'date' => 'datetime',
            'due_date' => 'datetime',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (RecurringInvoice $recurringInvoice) {
            $recurringInvoice->slug = Str::uuid()->toString();
            $recurringInvoice->invoice_number = time();
            $recurringInvoice->serial_number = self::max('serial_number') + 1;
            $recurringInvoice->code = 'RINV-' . Str::upper(Str::random(6)) . '-' . $recurringInvoice->serial_number;
        });
    }

    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }

    public function lineItems(): HasMany
    {
        return $this->hasMany(LineItem::class, 'recurring_invoice_id');
    }

    public function getRouteKeyName(): string
    {
        return 'slug';
    }

    protected function totalPrice(): Attribute
    {
        $totalPrice = $this->lineItems->sum(function ($item) {
            return $item->qty * $item->rate;
        });
        $discountAmount = ($totalPrice * $this->discount) / 100;
        $totalPrice -= $discountAmount;

        return Attribute::make(
            get: fn() => $totalPrice,
        );
    }

    protected function nextInvoiceDate(): Attribute
    {
        return Attribute::make(function () {
            $date = $this->date;
            return match ($this->recurrence_frequency) {
                'days' => $date->addDays($this->repeat_every),
                'weeks' => $date->addWeeks($this->repeat_every),
                'months' => $date->addMonths($this->repeat_every),
                'years' => $date->addYears($this->repeat_every),
                default => $date,
            };
        });
    }
}
