<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class RecurringInvoice extends Model
{
    protected $fillable = [
        'slug',
        'invoice_number',
        'serial_number',
        'code',
        'user_id',
        'date',
        'due_date',
        'recurrence_frequency',
        'repeat_every',
        'discount',
        'note',
        'status',
    ];

    protected function casts(): array
    {
        return [
            'slug' => 'string',
            'invoice_number' => 'timestamp',
            'date' => 'date',
            'due_date' => 'date',
        ];
    }

    protected static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (RecurringInvoice $recurringInvoice) {
            $recurringInvoice->slug = Str::uuid()->toString();
            $recurringInvoice->invoice_number = time();
            $recurringInvoice->serial_number = self::max('serial_number') + 1;
            $recurringInvoice->code = 'RINV-' . Str::upper(Str::random(6)) . '-' . $recurringInvoice->serial_number;
        });
    }
}
